remote_theme: pages-themes/cayman@v0.2.0
#theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme 

title: CPCB GSA
description: CMU-Pitt Computational Biology PhD Graduate Student Association

sections:
  - title: Documents
    path: ./documents.html
  - title: Calendar
    path: ./calendar.html
  - title: Meeting Minutes
    path: ./minutes.html
  - title: Constitution
    path: https://docs.google.com/document/d/1tQriag5fbN8yLRg5PV_3itHnHWbBr9MLHmkgQT9KQVs/edit?usp=sharing
  - title: People
    path: ./people.html
