remote_theme: pages-themes/cayman@v0.2.0
#theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme 

exclude:
  - Survey_Progress_Setup.md

title: CPCB GSA
description: CMU-Pitt Computational Biology PhD Graduate Student Association

sections:
  - title: Documents
    path: /documents.html
  - title: Calendar
    path: /calendar.html
  - title: Meeting Minutes
    path: /minutes.html
  - title: Constitution
    path: https://raw.githubusercontent.com/cpcb-gsa/Constitution/main/Constitution.pdf
  - title: People
    path: /gsa_people.html
