remote_theme: pages-themes/cayman@v0.2.0
#theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme 

title: CPCB GSA
description: CMU-Pitt Computational Biology PhD Graduate Student Association

sections:
  - title: Documents
    path:
  - title: Calendar
    path:
  - title: Meeting Minutes
    path:
  - title: Constitution
    path:
  - title: People
    path:
